#!/usr/bin/env python

import tvutils
import tvpickle
import getopt
import sys

def usage():
    print "Usage:"
    print "    tvpsend [options] <service_nr> <python expr>"
    print "    tvpsend -h"
    print ""
    print "Options:"
    print "    -h       This help."

def parse_opts():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.GetoptError, err:
        print str(err)
        usage()
        sys.exit(2)

    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()

    if len(args) < 2:
        print >>sys.stderr, "Expect a service_nr followed by python expression."
        usage()
        sys.exit(2)

    try:
        service_nr = int(args[0])
    except ValueError:
        print >>sys.stderr, "Expecting an integer service_nr."
        usage()
        sys.exit(2)

    try:
        send_expr = eval(" ".join(args[1:]))
    except Exception, err:
        print >>sys.stderr, "Could not parse expression. %s" % (err)
        usage()
        sys.exit(2)

    return service_nr, send_expr

def main():
    service_nr, send_expr = parse_opts()
    print service_nr, send_expr

if __name__ == "__main__":
    main()

